import type { NextPage } from "next";
import { signIn } from 'next-auth/react';
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <div className="flex flex-col justify-center center items-center">
          <button className="bg-violet-300 rounded-full border-gray-500 py-2 px-4 text-white hover:bg-violet-400 w-fit" onClick={() => signIn('discord')}>
            Sign in
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
